[package]
name = "aesdumpster"
version = "0.1.0"
edition = "2024"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = [
  "Win32_Foundation",
  "Win32_System_Console"
] }
winconsole = "0.11.1"

[target.'cfg(unix)'.dependencies]
  crossterm = "0.29.0"